### ISSUE TITLE
Pick a cool name

### ISSUE THREAD

**Issue by pavelk2** [CrowdCafe/CrowdBox#9]
- pixelman
- crowdbox
- dropcafe
- crowdpixel
- crowdfile
- crowdpaste
- pixelworker
- imageworker

**Comment by esseti** [comment]
Crowdpix
Pixelowd
Bitpixel
Snippetcrowd
Crowdpixelling
Crowdimaging

Il giovedì 16 ottobre 2014, Pavel Kucherbaev notifications@github.com ha
scritto:

> - pixelman
> - crowdbox
> - dropcafe
> - crowdpixel
> - crowdfile
> - crowdpaste
> - pixelworker
> - imageworker
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CrowdCafe/Pixelman/issues/9.

## 

Stefano - Sent with my thumbs

**Comment by pavelk2** [comment]
i think i will buy crowdbox.me (.me is free with github student pack)
